<?php

$aSidebars = array(
    'slider_args' => array(
        'name' => sprintf(__('Home Page Slider', $GLOBALS['sThemeTextDomain'])),
        'id' => 'slider-sidebar',
        'description' => 'Use a Text Widget to hold the slider shortcode',
        'class' => '',
        'before_widget' => '<div id="slider" class="widget %2$s ">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'right_args' => array(
        'name' => sprintf(__('Right-hand Internal Page Sidebar', $GLOBALS['sThemeTextDomain'])),
        'id' => 'right-sidebar',
        'description' => 'Content will be displayed on the right side of any page with sidebar option turned on.',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s module">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'archive_args' => array(
        'name' => sprintf(__('Blog Index Sidebar', $GLOBALS['sThemeTextDomain'])),
        'id' => 'archive-sidebar',
        'description' => 'Content will be displayed on the right side the Blog Index Page.',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s module">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'post_args' => array(
        'name' => sprintf(__('Post Sidebar', $GLOBALS['sThemeTextDomain'])),
        'id' => 'post-sidebar',
        'description' => 'Content will be displayed on the right side the Blog Index Page.',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s module">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'headerover_agrs' => array(
        'name' => sprintf(__('Header Override', $GLOBALS['sThemeTextDomain'])),
        'id' => 'headerover-sidebar',
        'description' => 'Content will be displayed instead of default Header',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s module header_widget">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'homepage_agrs' => array(
        'name' => sprintf(__('Homepage Button Bar', $GLOBALS['sThemeTextDomain'])),
        'id' => 'homepage-sidebar',
        'description' => 'Define Home page buttons here',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'footer1_args' => array(
        'name' => sprintf(__('Footer 1', $GLOBALS['sThemeTextDomain'])),
        'id' => 'footer1-sidebar',
        'description' => '',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'footer2_args' => array(
        'name' => sprintf(__('Footer 2', $GLOBALS['sThemeTextDomain'])),
        'id' => 'footer2-sidebar',
        'description' => '',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'footer3_args' => array(
        'name' => sprintf(__('Footer 3', $GLOBALS['sThemeTextDomain'])),
        'id' => 'footer3-sidebar',
        'description' => '',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'footer4_args' => array(
        'name' => sprintf(__('Footer 4', $GLOBALS['sThemeTextDomain'])),
        'id' => 'footer4-sidebar',
        'description' => '',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    ),
    'sub_args' => array(
        'name' => sprintf(__('Sub Footer', $GLOBALS['sThemeTextDomain'])),
        'id' => 'sub-sidebar',
        'description' => 'Content will appear under footer section',
        'class' => '',
        'before_widget' => '<div id="%1$s" class="widget %2$s align_center small">',
        'after_widget' => "</div>",
        'before_title' => '<h2 class="widgettitle">',
        'after_title' => "</h2>",
    )
);
foreach ($aSidebars as $args)
    register_sidebar($args);

